name: ChatManager
version: 1.2.2
main: com.flyaway.chatmanager.ChatManagerPlugin
api-version: "1.21"
author: FlyAwayMaking
website: https://github.com/flyawaymaking
depend: [LuckPerms]
description: Система управления сообщений чата

commands:
  chatmanager:
    description: Основная команда ChatManager
    usage: /<command> [reload|placeholders|colors|mentiontoggle|bc|send|help|info]
    aliases: [cm, chatm]

permissions:
  chatmanager.color.*:
    description: Права на доступ ко всем цветам ChatManager
    children:
      chatmanager.color.basic: true
      chatmanager.color.advanced: true
  chatmanager.format.*:
    description: Права на доступ ко всем форматам ChatManager
    children:
      chatmanager.format.italic: true
      chatmanager.format.bold: true
  chatmanager.*:
    description: Все права ChatManager
    children:
      chatmanager.color.*: true
      chatmanager.format.*: true
      chatmanager.bc: true
      chatmanager.send: true
      chatmanager.local.listen: true
      chatmanager.reload: true
  chatmanager.color.basic:
    description: Использование базовых цветов
    default: op
  chatmanager.color.advanced:
    description: Использование продвинутых цветов
    default: op
  chatmanager.format.italic:
    description: Использование курсива
    default: op
  chatmanager.format.bold:
    description: Использование жирного текста
    default: op
  chatmanager.reload:
    description: Перезагрузите конфигурацию плагина
    default: op
  chatmanager.local.listen:
    description: Получать сообщения из локальных чатов
    default: op
  chatmanager.bc:
    description: Отправка broadcast сообщений
    default: op
  chatmanager.send:
    description: Отправка сообщения игрока
    default: op
